apiVersion: v1
kind: Secret
metadata:
  name: whitesource
  labels:
    jenkins.io/created-by: jx
type: Opaque
data:
  api-key: {{ .Values.whitesource.apiKey }}
  user-key: {{ .Values.whitesource.userKey }}
  product-token: {{ .Values.whitesource.productToken }}
  project-token: {{ .Values.whitesource.projectToken }}
