apiVersion: v1
kind: Secret
metadata:
  name: whitesource
  labels:
    jenkins.io/created-by: jx
type: Opaque
data:
  api-key: vault:cosmin-prodsec/whitesource:api-key
  user-key: vault:cosmin-prodsec/whtiesource:user-key
  project-token: vault:cosmin-prodsec/whitesource:project-token
