apiVersion: v1
kind: Secret
metadata:
  name: whitesource
  labels:
    jenkins.io/created-by: jx
type: Opaque
data:
  api-key: {{ .Values.whitesource.apiKey | b64enc }}
  user-key: {{ .Values.whitesource.userKey | b64enc }}
