apiVersion: jenkins.io/v1
kind: SourceRepositoryGroup
metadata:
  name: whitesource-group
spec:
  scheduler:
    apiVersion: jenkins.io/v1
    kind: Scheduler
    name: whitesource-scheduler
  repositories: 
  - name: ccojocar-org-golang-prodsec
    kind: SourceRepository
