tekton:
{{- if eq .Requirements.webhook "prow" }}
  enabled: true
{{- else if eq .Requirements.webhook "lighthouse" }}
  enabled: true
{{- else }}
  enabled: false
{{- end }}

# Use cert-manager 0.11 CRDs/APIs with Dex
dex:
  certs:
    newApi: true

gitops:
  owner: {{ .Requirements.cluster.environmentGitOwner }}

whitesource:
  apiKey: vault:cosmin-prodsec/whitesource:api-key
  userKey: vault:cosmin-prodsec/whitesource:user-key
  productToken: vault:cosmin-prodsec/whitesource:product-token
  projectToken: vault:cosmin-prodsec/whitesource:project-token
